[workspace]
members = [
    "atomics",
    "clocksource",
    "heatmap",
    "histogram",
    "metriken",
    "metriken/derive",
    "ratelimit",
    "ringlog",
    "streamstats",
    "timer",
    "waterfall",
]

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
